[build]
  command = "pnpm --filter host-nuxt build"
  publish = "apps/host-nuxt/.output/public"

[build.environment]
  NODE_VERSION = "22"
  PNPM_VERSION = "10.30.2"
  PNPM_FLAGS = "--shamefully-hoist"